In [1]:
import pandas as pd
import numpy as np
import os
from utils import *

In [2]:
# Import library export data
data = pd.read_csv('data/goodreads_library_export.csv')

In [4]:
# Convert 'Date Read' column to datetime
data['Date Read'] = pd.to_datetime(data['Date Read'], format='%Y/%m/%d')

# Filter books read in 2023
books_read_in_2023 = data[data['Date Read'].dt.year == 2023]
# Sort by date read 
books_read_in_2023.sort_values(by='Date Read',ascending=False, inplace=True)

In [ ]:
user_id = os.environ.get('USERID')

# Scrape 'Date Started' info since it's not included in the export
dates1 = get_dates(user_id,'1')
dates2 = get_dates(user_id,'2')
dates2=dates2[0:17] 
dates = dates1 + dates2
parsed_dates=pd.to_datetime(dates)
formatted_dates = parsed_dates.strftime('%Y-%m-%d')

In [93]:
# Add as new column
books_read_in_2023['Date Added'] = formatted_dates

/var/folders/jg/nq2r_qk524gf7yxf_95q_tx80000gn/T/ipykernel_4779/2680125175.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books_read_in_2023['Date Added'] = formatted_dates

In [46]:
books_read_in_2023.head()

,Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,...,Date Read,Date Added,Bookshelves,Bookshelves with positions,Exclusive Shelf,My Review,Spoiler,Private Notes,Read Count,Owned Copies
2,64895,Cod: A Biography of the Fish that Changed the ...,Mark Kurlansky,"Kurlansky, Mark",NaN,"=""0099268701""","=""9780099268703""",2,3.92,Vintage/Ebury,...,2023-12-05,2023-11-05,NaN,NaN,read,I love a niche deep dive but this was missing ...,NaN,NaN,1,0
4,61431922,"Fourth Wing (The Empyrean, #1)",Rebecca Yarros,"Yarros, Rebecca",NaN,"=""1649374046""","=""9781649374042""",4,4.63,"Entangled Publishing, LLC (Red Tower Books)",...,2023-11-30,2023-11-22,NaN,NaN,read,"loved the plot, the world development, the cha...",NaN,NaN,1,0
8,63310838,Tomb Sweeping,Alexandra Chang,"Chang, Alexandra",NaN,"=""006295184X""","=""9780062951847""",3,3.79,Ecco Press,...,2023-11-22,2023-10-12,NaN,NaN,read,the story “persona development” hit me deep in...,NaN,NaN,1,0
9,51901147,The Ballad of Songbirds and Snakes (The Hunger...,Suzanne Collins,"Collins, Suzanne",NaN,"=""""","=""""",4,3.91,Scholastic Press,...,2023-11-17,2023-11-22,NaN,NaN,read,finished 1 hour before seeing the movie,NaN,NaN,1,0
10,3181564,The Housekeeper and the Professor,Yōko Ogawa,"Ogawa, Yōko",Stephen Snyder,"=""0312427808""","=""9780312427801""",3,4.05,Picador,...,2023-11-02,2023-09-18,NaN,NaN,read,good one for my reading rut,NaN,NaN,1,0

In [65]:
# Export parsed data
books_read_in_2023.to_csv('goodreads_read_parsed.csv',index=False)